
learner         :       GSA_SDP
optim           :       Adam
learning_rate   :       0.0005
momentum        :       0
weight_decay    :       0
dataset         :       imagenet100
n_tasks         :       20
mem_size        :       10000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
tf_type         :       partial
training_type   :       blurry
blurry_scale    :       500
sdp_c2          :       0.75
sdp_mu          :       100
